version: '3.8'
services:
  baf:
    build: .
    container_name: baf
    environment:
      VNC_PASSWORD_FILE: /run/secrets/vnc_password
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_USER: postgres
      POSTGRES_DB: experiment
    secrets:
      - vnc_password
      - db_password
    ports:
      - '55902:5900'
      - '55433:5432' # TODO: move to a DB container
      - '58888:8888' # Jupyer Lab Server; TODO: maybe move to an optional container as well?

secrets:
  db_password:
    file: secrets/db_password.txt
  vnc_password:
    file: secrets/vnc_password.txt
